{% set name = "orange-canvas-core" %}
{% set version = "0.1.24" %}
{% set sha256 = "dfd9d604d61ec6c4b261357496b41c434325d1ef386f0615406c1536dbd76d54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip    >=18.0
    - setuptools
    - anyqt >=0.0.13
    - pyqt
    - docutils
    - commonmark >=0.8.1
    - requests
    - cachecontrol >=0.12.6
    # via cachecontrol[filecache]
    - lockfile >=0.9
    - dictdiffer
    - qasync
    - importlib_metadata

test:
  imports:
    - orangecanvas.main
    - orangecanvas.application.canvasmain

about:
  home: https://github.com/biolab/orange-canvas-core
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Core component of Orange Canvas

  description: |
    Orange Canvas Core is is a framework for building graphical user
    interfaces for editing workflows. It is a component used to build
    the Orange Canvas (http://orange.biolab.si) data-mining application
    (for which it was developed in the first place).

  doc_url: https://orange-canvas-core.readthedocs.io/
  dev_url: https://github.com/biolab/orange-canvas-core

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
